language: perl
perl:
   - "5.20"
   - "5.18"
   - "5.16"

install:
   # XXX: turn release testing back on when ::Server is released
   - export RELEASE_TESTING= AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls
   - cpanm --quiet --notest --installdeps .

script:
   - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
   - cover

after_success:
  - cover -report coveralls
