requires 'Sereal::Decoder';
requires 'IO::Async';
requires 'Log::Contextual';
requires 'Log::Log4perl';
requires 'Try::Tiny';
requires 'DBIx::Class';
requires 'DBIx::Class::Helpers';
requires 'DBIx::Class::Candy';
requires 'Sereal::Decoder';
